### ISSUE TITLE
Error 'Couldn't resolve host name' and with: attribute is blank

### ISSUE THREAD

**Issue by bennymeade** [testspace-com/setup-testspace#9]
I've authorised TestSpace for one of my repos, URL example: https://github.com/bennymeade/testing-testspace
I've then added the required steps to my GH workflow:

```
- name: TestSpace client
        if: always()
        // Just for the record I also tried `uses: testspace-com/setup-testspace@v1`
        uses: testspace-com/setup-testspace@v1.0.4
        with:
          domain: ${{ github.bennymeade.testspace.com }}

- name: Publish Results to Testspace
        if: always()
        run: |
          testspace results.xml

```

But I get the following error:
```
Run testspace-com/setup-testspace@v1.0.4
  with:
testspace
Testspace Client, version 2.8.5013
Copyright (C) 2021 S2 Technologies, Inc.

Unable to proceed. Unable to access "testspace-config" space in "bennymeade:testing-testspace" project at Testspace (https://.testspace.com) with specified credentials. Failed performing request: [6] Couldn't resolve host name
For more information about Testspace, visit www.testspace.com.
Error: Process completed with exit code 2.
```
Note that the ```with: ``` is blank and causes ```project at Testspace (https://.testspace.com) with specified credentials```
